LEGAL_DATABASE = [
    {
        "id": "SC-CR-01",
        "title": "Defective Electronic Product",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "Customer bought a smartphone that stopped working within 3 days.",
        "user_input_examples": [
            "My phone stopped working in 3 days",
            "Seller refused replacement",
            "Product is defective",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to be protected against defective goods",
        "action_steps": "Request replacement/refund -> Contact platform -> File complaint",
        "timeline": "Within warranty/return period",
        "risks": "Seller denies defect, delays, blames misuse",
        "edge_cases": "Physical damage vs manufacturing defect; no bill/invoice",
        "clarification_questions": "Is product under warranty? Do you have proof of purchase?",
        "source": "Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-02",
        "title": "Expired Packaged Food",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": (
            "Customer purchased packaged food that was already expired and unsafe to consume."
        ),
        "user_input_examples": [
            "I bought expired food",
            "Product is unsafe to consume",
        ],
        "applicable_laws": "Food Safety and Standards Act, 2006; Consumer Protection Act, 2019",
        "rights": "Right to safety.",
        "action_steps": "Return product -> Report seller -> File complaint with food authority",
        "timeline": "Immediate",
        "risks": "Health issues, seller denial",
        "edge_cases": "Opened vs sealed product",
        "clarification_questions": "Is product expired on label?",
        "source": "FSSAI Act 2006; Consumer Protection Act 2019",
    },
    {
        "id": "SC-CR-03",
        "title": "Online Payment Fraud",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": (
            "Customer made an online payment, but money was deducted without order confirmation."
        ),
        "user_input_examples": [
            "Money deducted but no order",
            "Payment failed but money gone",
        ],
        "applicable_laws": "Information Technology Act, 2000; Reserve Bank of India guidelines",
        "rights": "Right to secure transactions",
        "action_steps": "Report to bank -> Block transaction -> File complaint",
        "timeline": "Immediate",
        "risks": "Delay in refund, poor response from bank",
        "edge_cases": "UPI vs card payment",
        "clarification_questions": "Which payment method used?",
        "source": "IT Act 2000; RBI Guidelines",
    },
    {
        "id": "SC-CR-04",
        "title": "Misleading Advertisement",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": (
            "Product advertised with false claims (e.g., '100% organic') but contains chemicals."
        ),
        "user_input_examples": [
            "Product claims were false",
            "It said 100% organic but it's not",
            "I was misled by advertisement",
        ],
        "applicable_laws": (
            "Consumer Protection Act, 2019; Advertising Standards Council of India guidelines"
        ),
        "rights": "Right to be informed",
        "action_steps": "Request refund -> Report advertisement -> File complaint",
        "timeline": "As soon as issue is identified",
        "risks": "False marketing, hidden facts",
        "edge_cases": "Influencer promotions, hidden disclaimers",
        "clarification_questions": "Do you have proof of advertisement?",
        "source": "Consumer Protection Act 2019; ASCI Guidelines",
    },
    {
        "id": "SC-CR-05",
        "title": "Underweight Packaged Goods",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "A packaged product shows 1kg on label but contains less quantity.",
        "user_input_examples": [
            "Product quantity is less than mentioned",
            "1kg packet contains less",
        ],
        "applicable_laws": "Legal Metrology Act, 2009; Consumer Protection Act",
        "rights": "Right to fair trade practices",
        "action_steps": "Report seller -> File complaint -> Demand compensation",
        "timeline": "Immediate",
        "risks": "Mislabelling, cheating consumers",
        "edge_cases": "Packaging error, measurement confusion",
        "clarification_questions": "Did you measure the product?",
        "source": "Legal Metrology Act 2009; Consumer Protection Act 2019",
    },
    {
        "id": "SC-CR-06",
        "title": "Telecom Service Failure",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "Customer pays for premium plan but faces continuous network issues.",
        "user_input_examples": [
            "Network not working",
            "I paid but service is poor",
        ],
        "applicable_laws": "TRAI Guidelines; Consumer Protection Act, 2019",
        "rights": "Right to quality service",
        "action_steps": "File complaint with provider -> Escalate to TRAI -> Seek compensation",
        "timeline": "Within service period",
        "risks": "Ignored complaints, unresolved service",
        "edge_cases": "Temporary network issue, location-based problem",
        "clarification_questions": "Is issue continuous or temporary?",
        "source": "TRAI Guidelines; Consumer Protection Act 2019",
    },
    {
        "id": "SC-CR-07",
        "title": "Refund Delay in E-commerce",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "Customer returns products but refund is delayed beyond promised timeline.",
        "user_input_examples": [
            "Refund not received",
            "Return accepted but no money",
        ],
        "applicable_laws": "Consumer Protection Act, 2019; RBI Guidelines",
        "rights": "Right to timely redressal; right to refund",
        "action_steps": "1. Contact platform 2. Escalate complaint 3. File consumer complaint",
        "timeline": "Within promised refund period",
        "risks": "Delay increases dispute complexity",
        "edge_cases": "Payment method issues",
        "clarification_questions": "When was the return processed?",
        "source": "Consumer Protection Act 2019; RBI Guidelines",
    },
    {
        "id": "SC-CR-08",
        "title": "Unauthorized Subscription Charges",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "Customer is charged automatically after free trial without clear consent.",
        "user_input_examples": [],
        "applicable_laws": "Consumer Protection Act; IT Act, 2000",
        "rights": "Right to informed consent",
        "action_steps": "Cancel subscription -> Request refund -> Report platform",
        "timeline": "Immediate",
        "risks": "Hidden terms, unclear policies",
        "edge_cases": "Hidden terms",
        "clarification_questions": "Did you agree to terms?",
        "source": "Consumer Protection Act 2019; IT Act 2000",
    },
    {
        "id": "SC-CR-09",
        "title": "Product Not Delivered but Marked Delivered",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "Order marked delivered but customer never received it.",
        "user_input_examples": [
            "Order shows delivered but I didn't receive it",
            "Delivery issue",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to proper service",
        "action_steps": "Report immediately -> Contact platform -> File complaint",
        "timeline": "Immediate",
        "risks": "Delivery disputes, lack of proof",
        "edge_cases": "Delivered to wrong person",
        "clarification_questions": "Did you receive delivery proof?",
        "source": "Consumer Protection Act 2019",
    },
    {
        "id": "SC-CR-10",
        "title": "Warranty Claim Denied",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": (
            "Product fails within warranty period, but company refuses repair claiming misuse."
        ),
        "user_input_examples": [
            "Warranty claim rejected",
            "Company says misuse",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to after-sales service",
        "action_steps": "Request inspection -> File complaint -> Seek legal remedy",
        "timeline": "Immediate",
        "risks": "False claims, refusal without inspection",
        "edge_cases": "Physical damage",
        "clarification_questions": "Is product under warranty?",
        "source": "Consumer Protection Act 2019",
    },
    {
        "id": "SC-CR-11",
        "title": "Price Charged Above MRP",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "Customer is charged more than the Maximum Retail Price (MRP) on a packaged product.",
        "user_input_examples": [
            "Shop charged more than MRP",
            "I paid extra for packaged product",
        ],
        "applicable_laws": "Legal Metrology Act, 2009; Consumer Protection Act, 2019",
        "rights": "Right to fair pricing; right against unfair trade practices",
        "action_steps": "1. Show MRP on packaging 2. Ask for refund of excess amount 3. File complaint with consumer forum",
        "timeline": "Immediate",
        "risks": "Seller denial",
        "edge_cases": "Restaurant pricing vs packaged goods",
        "clarification_questions": "Was it a packaged item?",
        "source": "Legal Metrology Act, 2009",
    },
    {
        "id": "SC-CR-12",
        "title": "No Refund Policy Issue",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "Seller refuses refund citing 'no refund policy' even in valid cases.",
        "user_input_examples": [
            "They said no refund allowed",
            "Shop refused refund",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to refund in defective cases",
        "action_steps": "1. Request written policy 2. Escalate complaint 3. File case",
        "timeline": "Immediate",
        "risks": "Misleading policies",
        "edge_cases": "Exchange vs refund",
        "clarification_questions": "Was product defective?",
        "source": "Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-13",
        "title": "Fake Discount / Misleading Sale",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": (
            "Product advertised at a discounted price, but the 'original price' appears "
            "inflated, making the discount misleading."
        ),
        "user_input_examples": [
            "This sale looks fake",
            "They increased price before giving discount",
            "Discount is not real",
        ],
        "applicable_laws": "Consumer Protection Act, 2019 (Unfair Trade Practices)",
        "rights": "Right to be informed; right to protection against unfair trade practices; right to fair pricing",
        "action_steps": (
            "1. Compare product prices across platforms 2. Take screenshots of misleading "
            "pricing 3. Report the issue to the platform 4. File complaint with consumer "
            "forum if necessary"
        ),
        "timeline": "As soon as misleading pricing is identified",
        "risks": "Financial loss due to deceptive pricing; difficulty proving intent",
        "edge_cases": "Dynamic pricing vs intentional misleading; seasonal discounts",
        "clarification_questions": "Was the original price clearly shown? Did you compare with other sellers?",
        "source": "Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-14",
        "title": "Damaged Product Delivered",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "User received a product that is physically damaged or not usable at the time of delivery.",
        "user_input_examples": [
            "I received a broken item",
            "Product arrived damaged",
            "Package was damaged on delivery",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to receive goods in proper condition; right to replacement or refund; right to file complaint",
        "action_steps": (
            "1. Take photos/videos of the product 2. Report issue to seller/platform "
            "immediately 3. Request replacement or refund 4. Escalate to consumer forum if denied"
        ),
        "timeline": "Within return/replacement window (usually 7-10 days)",
        "risks": "Claim rejection due to delay; seller denial",
        "edge_cases": "Transit damage vs user damage; open-box delivery cases",
        "clarification_questions": "Did you report the damage immediately? Was packaging tampered?",
        "source": "Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-15",
        "title": "Wrong Product Delivered",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "The product delivered does not match the item ordered by the user.",
        "user_input_examples": [
            "I received a different product",
            "Wrong item delivered",
            "Product does not match order",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to correct goods; right to replacement or refund",
        "action_steps": (
            "1. Take evidence (photos/screenshots) 2. Report mismatch to seller "
            "3. Request replacement/refund 4. File complaint if unresolved"
        ),
        "timeline": "Within return window",
        "risks": "Return request denial; delayed resolution",
        "edge_cases": "Similar-looking products; user ordering error",
        "clarification_questions": "Does invoice match product received?",
        "source": "Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-16",
        "title": "Unfair Cancellation Charges",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "User is charged excessive or hidden cancellation fees that were not clearly disclosed.",
        "user_input_examples": [
            "They charged high cancellation fees",
            "Refund deducted unfairly",
            "I was charged without reason",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to transparency; right against unfair trade practices",
        "action_steps": "1. Review terms and conditions 2. Contact customer support 3. Raise complaint 4. Approach consumer forum",
        "timeline": "Immediate",
        "risks": "Financial loss; hidden policies",
        "edge_cases": "Partial refunds; dynamic cancellation fees",
        "clarification_questions": "Were charges disclosed earlier?",
        "source": "Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-17",
        "title": "Warranty Claim Denied (Service Center Refusal)",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "User is denied warranty service despite product being within warranty period.",
        "user_input_examples": [
            "My warranty claim was rejected",
            "Product is under warranty but they refused",
            "Service center denied repair",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to warranty service; right to fair service",
        "action_steps": "1. Check warranty terms 2. Contact company 3. Escalate complaint 4. File consumer complaint",
        "timeline": "Within warranty period",
        "risks": "Misinterpretation of terms; lack of proof",
        "edge_cases": "Physical damage vs manufacturing defect",
        "clarification_questions": "Is product still under warranty?",
        "source": "Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-18",
        "title": "Hidden Subscription Charges",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "User is charged for a subscription that was auto-renewed or not clearly disclosed.",
        "user_input_examples": [
            "Money deducted automatically",
            "Subscription renewed without consent",
            "I didn't sign up for this",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to informed consent; right against unfair billing",
        "action_steps": "1. Cancel subscription immediately 2. Contact service provider 3. Request refund 4. File complaint if needed",
        "timeline": "Immediate",
        "risks": "Repeated deductions; hidden terms",
        "edge_cases": "Free trial auto-renewal",
        "clarification_questions": "Did you agree to auto-renewal?",
        "source": "Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-19",
        "title": "Poor After-Sales Service",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "User is unable to get proper support or service after purchasing a product.",
        "user_input_examples": [
            "No support after purchase",
            "Customer care not responding",
            "Product issue not resolved",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to service; right to grievance redressal",
        "action_steps": "1. Contact customer support 2. Escalate complaint 3. Use consumer helpline 4. File complaint",
        "timeline": "Within reasonable time",
        "risks": "Delayed resolution; lack of accountability",
        "edge_cases": "Service vs product issue",
        "clarification_questions": "How long has the issue been pending?",
        "source": "Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-20",
        "title": "Misleading Product Description",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "The product received does not match the description, features, or specifications advertised.",
        "user_input_examples": [
            "Product is not as described",
            "Features were different",
            "Online description was wrong",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to accurate information; right to fair trade",
        "action_steps": "1. Compare product with listing 2. Collect evidence 3. Request refund/replacement 4. File complaint",
        "timeline": "Within return window",
        "risks": "Seller denial; difficulty proving mismatch",
        "edge_cases": "Minor variation vs major difference",
        "clarification_questions": "What exactly was different?",
        "source": "Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-21",
        "title": "Food Safety Violation (Contaminated or Unsafe Food)",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "User consumed or received food that is contaminated, expired, or unsafe, posing a health risk.",
        "user_input_examples": [
            "I found something in my food",
            "Food made me sick",
            "Restaurant served unsafe food",
        ],
        "applicable_laws": "Food Safety and Standards Act, 2006 (FSSAI Act); Consumer Protection Act, 2019",
        "rights": "Right to safe and hygienic food; right to complain against unsafe products; right to compensation for harm",
        "action_steps": (
            "1. Preserve the food sample (if possible) 2. Take photos/videos as evidence "
            "3. Report to restaurant/vendor 4. File complaint on FSSAI portal or consumer forum"
        ),
        "timeline": "Immediate or as soon as illness/issue is noticed",
        "risks": "Health complications; difficulty proving contamination",
        "edge_cases": "Food spoilage due to delay; allergy vs contamination",
        "clarification_questions": "Did the food cause illness? Was it packaged or freshly served?",
        "source": "FSSAI Act, 2006; Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-22",
        "title": "Overcharging by Cab or Ride Service",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "User was charged more than the displayed or agreed fare during a ride service.",
        "user_input_examples": [
            "Cab driver charged more than shown",
            "I paid higher than app fare",
            "Extra charges added unfairly",
        ],
        "applicable_laws": "Consumer Protection Act, 2019; Motor Vehicles Act",
        "rights": "Right to fair pricing; right to transparent billing; right to complaint",
        "action_steps": "1. Check fare details in the app 2. Take screenshot of fare breakdown 3. Report issue to service provider 4. File complaint if unresolved",
        "timeline": "Immediate or within same day",
        "risks": "Small amount disputes ignored; lack of proof",
        "edge_cases": "Surge pricing vs unfair charge; cash vs digital payment",
        "clarification_questions": "Was the final fare different from app estimate?",
        "source": "Consumer Protection Act, 2019; Motor Vehicles Act",
    },
    {
        "id": "SC-CR-23",
        "title": "Sale of Fake or Duplicate Medicines",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "User suspects that the medicine purchased is counterfeit, expired, or not genuine.",
        "user_input_examples": [
            "I think I got fake medicine",
            "Medicine is not working",
            "Packaging looks suspicious",
        ],
        "applicable_laws": "Drugs and Cosmetics Act, 1940; Consumer Protection Act, 2019",
        "rights": "Right to safe and genuine products; right to file complaint; right to compensation",
        "action_steps": (
            "1. Stop using the medicine immediately 2. Preserve packaging and bill "
            "3. Report to pharmacist and drug authority 4. File complaint with drug "
            "inspector or consumer forum"
        ),
        "timeline": "Immediate",
        "risks": "Serious health consequences; difficulty verifying authenticity",
        "edge_cases": "Side effects vs fake medicine; expired vs counterfeit",
        "clarification_questions": "Was the medicine purchased from a licensed store?",
        "source": "Drugs and Cosmetics Act, 1940; Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-24",
        "title": "Gym Membership Fraud / Service Not Provided",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "User paid for a gym or service membership, but the service is unavailable, discontinued, or not as promised.",
        "user_input_examples": [
            "Gym closed after I paid",
            "I paid membership but no service",
            "Gym not providing promised facilities",
        ],
        "applicable_laws": "Consumer Protection Act, 2019",
        "rights": "Right to receive promised service; right to refund; right to file complaint",
        "action_steps": "1. Contact gym management 2. Request refund or service continuation 3. Document communication 4. File complaint if unresolved",
        "timeline": "Within reasonable time after issue",
        "risks": "Financial loss; service provider shutting down",
        "edge_cases": "Temporary closure vs permanent shutdown; partial service provided",
        "clarification_questions": "Was the service stopped completely?",
        "source": "Consumer Protection Act, 2019",
    },
    {
        "id": "SC-CR-25",
        "title": "Online Course / Digital Service Scam",
        "category": "Consumer Rights",
        "jurisdiction": "India",
        "situation": "User paid for an online course or digital service but did not receive access or promised content.",
        "user_input_examples": [
            "I paid for a course but didn't get access",
            "Online class not delivered",
            "Platform is not responding",
        ],
        "applicable_laws": "Consumer Protection Act, 2019; Information Technology Act (for online transactions)",
        "rights": "Right to receive paid service; right to refund; right to grievance redressal",
        "action_steps": "1. Check payment confirmation 2. Contact platform support 3. Send formal complaint 4. File complaint on consumer forum",
        "timeline": "Immediate or within few days of non-delivery",
        "risks": "Scam platforms disappearing; no refund",
        "edge_cases": "Technical issue vs scam; delayed access vs non-delivery",
        "clarification_questions": "Did you receive any confirmation or login access?",
        "source": "Consumer Protection Act, 2019; IT Act",
    },
    {
        "id": "SC-SH-01",
        "title": "Online Harassment and Threats",
        "category": "Safety & Harassment (Cyber)",
        "jurisdiction": "India",
        "situation": "User is facing abusive messages or threats through online platforms.",
        "user_input_examples": [
            "Someone is abusing me on Instagram",
            "I am getting threatening messages online",
            "A person is harassing me on WhatsApp",
        ],
        "applicable_laws": (
            "IPC Section 354D (Stalking); IPC Section 507 (Criminal intimidation by "
            "anonymous communication); IT Act Section 66E (Violation of privacy); "
            "IT Act Section 67 (Publishing/transmitting obscene content)"
        ),
        "rights": (
            "User has the right to report cyber harassment. User can file a complaint "
            "with the cyber crime portal or police. Identity and privacy must be "
            "protected during investigation."
        ),
        "action_steps": (
            "1. Take screenshots of messages as evidence 2. Block the offender on the "
            "platform 3. Report the account on the platform 4. File complaint on cyber "
            "crime portal (cybercrime.gov.in) 5. Visit police station if threats are serious"
        ),
        "timeline": "Report immediately; early reporting improves action chances.",
        "risks": "Ignoring may escalate harassment; loss of evidence if messages are deleted",
        "edge_cases": "Anonymous accounts; known person vs stranger; threat vs casual abuse",
        "clarification_questions": (
            "Is the person known to you? Are there threats involved or just abusive language?"
        ),
        "source": "IT Act Sec 66E, Sec 67; IPC Sec 354D, Sec 507",
    },
    {
        "id": "SC-SH-02",
        "title": "Stalking in Public",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is being repeatedly followed causing fear.",
        "user_input_examples": [
            "Someone keeps following me",
            "A person stalks me daily",
            "I feel unsafe outside",
        ],
        "applicable_laws": "IPC Sec 354D; IPC Sec 506",
        "rights": "Right to safety; right to file complaint",
        "action_steps": (
            "1. Inform trusted person 2. Note details of suspect "
            "3. Visit police station 4. File complaint/FIR"
        ),
        "timeline": "Report early",
        "risks": "Escalation to physical harm",
        "edge_cases": "Known person; one-time vs repeated",
        "clarification_questions": "Is it repeated? Do you know the person?",
        "source": "IPC Sec 354D, Sec 506",
    },
    {
        "id": "SC-SH-03",
        "title": "Workplace Harassment",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is facing harassment at workplace/internship.",
        "user_input_examples": [
            "My boss sends inappropriate texts",
            "I feel uncomfortable at internship",
        ],
        "applicable_laws": "POSH Act 2013; IPC Sec 354A",
        "rights": "Right to safe workplace; right to file complaint",
        "action_steps": "1. Save evidence 2. Report to HR/ICC 3. File complaint if unresolved",
        "timeline": "Report promptly",
        "risks": "Continued harassment",
        "edge_cases": "No HR system; informal workplace",
        "clarification_questions": "Is there an internal committee?",
        "source": "POSH Act 2013; IPC Sec 354A",
    },
    {
        "id": "SC-SH-04",
        "title": "Threat of Sharing Private Photos",
        "category": "Safety & Harassment (Cyber)",
        "jurisdiction": "India",
        "situation": "User is being blackmailed using private content.",
        "user_input_examples": [
            "Someone is blackmailing me with photos",
            "They are threatening to leak my images",
        ],
        "applicable_laws": "IPC Sec 384; IPC Sec 503; IT Act Sec 66E, Sec 67",
        "rights": "Right to privacy; right to file complaint",
        "action_steps": (
            "1. Do not comply 2. Save evidence 3. Report to cyber cell 4. File police complaint"
        ),
        "timeline": "Immediate action required",
        "risks": "Content misuse; emotional distress",
        "edge_cases": "Known person; edited images",
        "clarification_questions": "Has anything been shared already?",
        "source": "IPC Sec 384, Sec 503; IT Act Sec 66E, Sec 67",
    },
    {
        "id": "SC-SH-05",
        "title": "Harassment in Public Transport",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User faced inappropriate physical contact in public.",
        "user_input_examples": [
            "Someone touched me in bus",
            "I was harassed in metro",
        ],
        "applicable_laws": "IPC Sec 354; IPC Sec 509",
        "rights": "Right to safety; right to report immediately",
        "action_steps": "1. Raise alarm 2. Inform authorities 3. File complaint",
        "timeline": "Immediate",
        "risks": "Repeated incidents",
        "edge_cases": "Crowded area; unknown accused",
        "clarification_questions": "Can you identify the person?",
        "source": "IPC Sec 354, Sec 509",
    },
    {
        "id": "SC-SH-06",
        "title": "Verbal Abuse and Threats",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User faced verbal abuse or intimidation.",
        "user_input_examples": [
            "Someone threatened me",
            "I was verbally abused",
        ],
        "applicable_laws": "IPC Sec 503; IPC Sec 506; IPC Sec 509",
        "rights": "Right to dignity; right to complain",
        "action_steps": "1. Record evidence if possible 2. Report to police 3. Avoid confrontation",
        "timeline": "As soon as possible",
        "risks": "Escalation",
        "edge_cases": "Public vs private setting",
        "clarification_questions": "Was there a threat of harm?",
        "source": "IPC Sec 503, Sec 506, Sec 509",
    },
    {
        "id": "SC-SH-07",
        "title": "Harassing Phone Calls",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User receives repeated unwanted calls.",
        "user_input_examples": [
            "I get disturbing calls",
            "Unknown number keeps calling",
        ],
        "applicable_laws": "IPC Sec 507",
        "rights": "Right to privacy; right to report",
        "action_steps": "1. Block number 2. Report to telecom provider 3. File complaint",
        "timeline": "Immediate",
        "risks": "Continued harassment",
        "edge_cases": "Multiple numbers",
        "clarification_questions": "Is it repeated?",
        "source": "IPC Sec 507",
    },
    {
        "id": "SC-SH-08",
        "title": "Bullying and Group Threats",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is facing intimidation from multiple people.",
        "user_input_examples": [
            "A group is threatening me",
            "People are spreading rumors",
        ],
        "applicable_laws": "IPC Sec 503; IPC Sec 506; IPC Sec 500",
        "rights": "Right to protection; right to complain",
        "action_steps": "1. Collect evidence 2. Report to authority/police 3. Seek support",
        "timeline": "Early reporting",
        "risks": "Escalation",
        "edge_cases": "Online vs offline",
        "clarification_questions": "Is it online or offline?",
        "source": "IPC Sec 503, Sec 506, Sec 500",
    },
    {
        "id": "SC-SH-09",
        "title": "Neighbor Harassment",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is facing repeated harassment from neighbor.",
        "user_input_examples": [
            "Neighbor keeps harassing me",
            "Someone nearby makes comments",
        ],
        "applicable_laws": "IPC Sec 503; IPC Sec 506; IPC Sec 509",
        "rights": "Right to peaceful living",
        "action_steps": "1. Warn or report locally 2. File complaint if continues",
        "timeline": "If repeated",
        "risks": "Ongoing conflict",
        "edge_cases": "Shared property",
        "clarification_questions": "Is it repeated behavior?",
        "source": "IPC Sec 503, Sec 506, Sec 509",
    },
    {
        "id": "SC-SH-10",
        "title": "Unsafe Public Situation / Feeling Threatened",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User feels threatened or unsafe in environment.",
        "user_input_examples": [
            "I feel unsafe in an area",
            "Someone is behaving suspiciously",
        ],
        "applicable_laws": "IPC Sec 506",
        "rights": "Right to safety",
        "action_steps": "1. Move to safe place 2. Contact helpline/police 3. Inform trusted person",
        "timeline": "Immediate",
        "risks": "Potential harm",
        "edge_cases": "No direct incident yet",
        "clarification_questions": "Is there an immediate threat?",
        "source": "IPC Sec 506",
    },
    {
        "id": "SC-SH-11",
        "title": "Revenge Porn / Non-Consensual Image Sharing",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": (
            "User's private or intimate images/videos have been shared or are being "
            "threatened to be shared online without consent, causing serious privacy "
            "and safety concerns."
        ),
        "user_input_examples": [
            "My private photos were shared online",
            "Someone leaked my pictures without permission",
            "My ex is threatening to upload my videos",
        ],
        "applicable_laws": (
            "Information Technology Act, 2000 - Section 66E (Violation of Privacy); "
            "IT Act - Section 67, 67A (Publishing obscene/sexually explicit content); "
            "Indian Penal Code - Section 354C (Voyeurism); IPC Section 509 (Insult to modesty)"
        ),
        "rights": (
            "Right to privacy and dignity; right to file a cybercrime complaint; right "
            "to get the content removed; right to protection from harassment"
        ),
        "action_steps": (
            "1. Take screenshots and save links as evidence 2. Report the content on "
            "the platform immediately 3. File complaint on cybercrime portal "
            "(cybercrime.gov.in) 4. Visit nearest police station if threat continues "
            "5. Inform a trusted adult/guardian"
        ),
        "timeline": "Immediate action is critical to prevent further spread",
        "risks": "Content may spread rapidly; emotional and reputational harm; delay reduces chances of removal",
        "edge_cases": "Morphed or edited images; anonymous accounts",
        "clarification_questions": "Has the content already been posted or only threatened? Do you know the person responsible?",
        "source": "IT Act Sec 66E, 67, 67A; IPC Sec 354C, 509",
    },
    {
        "id": "SC-SH-12",
        "title": "Fake Social Media Account (Impersonation)",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "A fake account has been created impersonating the user, which may lead to misuse of identity and reputation damage.",
        "user_input_examples": [
            "Someone created a fake account using my name",
            "My photos are being used in another profile",
            "A fake ID is pretending to be me",
        ],
        "applicable_laws": "IT Act Section 66C (Identity Theft); IPC Section 419 (Cheating by impersonation)",
        "rights": "Right to identity protection; right to report and remove fake accounts; right to file complaint",
        "action_steps": "1. Report the fake account on the platform 2. Take screenshots as evidence 3. File complaint on cybercrime portal 4. Inform friends to report the account",
        "timeline": "Immediate",
        "risks": "Reputation damage; fraud in user's name",
        "edge_cases": "Parody accounts vs harmful impersonation",
        "clarification_questions": "Is the account pretending to be you or just similar?",
        "source": "IT Act Sec 66C; IPC Sec 419",
    },
    {
        "id": "SC-SH-13",
        "title": "Sexual Harassment in Educational Institution",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": (
            "User is experiencing unwelcome behavior such as inappropriate comments, "
            "gestures, or actions in an educational institution, affecting their safety "
            "and well-being."
        ),
        "user_input_examples": [
            "A teacher/student is behaving inappropriately with me",
            "I feel uncomfortable due to someone's actions in college",
            "I am facing harassment in school",
        ],
        "applicable_laws": (
            "Sexual Harassment of Women at Workplace (Prevention, Prohibition and "
            "Redressal) Act, 2013 (POSH Act); UGC (Prevention, Prohibition and Redressal "
            "of Sexual Harassment) Regulations, 2015; IPC Section 354A (Sexual harassment)"
        ),
        "rights": (
            "Right to a safe and respectful educational environment; right to file a "
            "complaint with the Internal Complaints Committee (ICC); right to "
            "confidentiality during proceedings; right to protection from retaliation"
        ),
        "action_steps": (
            "1. Document the incident with date, time, and details 2. Report the matter "
            "to school/college authority or ICC 3. Submit a formal written complaint "
            "4. Escalate to higher authorities if no action is taken 5. Seek support "
            "from a trusted adult/guardian"
        ),
        "timeline": "Complaint should ideally be filed within 3 months of the incident",
        "risks": "Fear of retaliation or backlash; emotional distress; delay may weaken the case",
        "edge_cases": "Verbal harassment vs physical misconduct; harassment by peer vs authority figure",
        "clarification_questions": "Did the incident happen within the institution? Is the person part of the institution?",
        "source": "POSH Act, 2013; UGC Regulations 2015; IPC Sec 354A",
    },
    {
        "id": "SC-SH-14",
        "title": "Blackmail / Extortion Threat",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is being threatened or coerced into giving money or doing something under fear of harm, exposure, or damage to reputation.",
        "user_input_examples": [
            "Someone is blackmailing me for money",
            "I am being threatened to pay or something bad will happen",
            "They said they will leak my information if I don't comply",
        ],
        "applicable_laws": "IPC Section 384 (Extortion); IPC Section 503 (Criminal intimidation); IPC Section 506 (Punishment for criminal intimidation)",
        "rights": "Right to personal safety; right to refuse illegal demands; right to file an FIR; right to police protection",
        "action_steps": (
            "1. Do not comply with the demands 2. Save all messages, calls, or evidence "
            "3. Avoid further direct interaction 4. File FIR at nearest police station "
            "5. Report cybercrime if online blackmail"
        ),
        "timeline": "Immediate action is recommended",
        "risks": "Escalation of threats; financial loss; emotional distress",
        "edge_cases": "Known person vs unknown attacker; online vs offline blackmail",
        "clarification_questions": "Is the threat ongoing? Has any money already been paid?",
        "source": "IPC Sec 384, 503, 506",
    },
    {
        "id": "SC-SH-15",
        "title": "Unauthorized Video Recording",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User has been recorded without consent, especially in a private or sensitive setting, violating their privacy and dignity.",
        "user_input_examples": [
            "Someone recorded me without my permission",
            "I found a hidden camera in a changing room",
            "A video of me was taken secretly",
        ],
        "applicable_laws": "IPC Section 354C (Voyeurism); IT Act Section 66E (Violation of Privacy)",
        "rights": "Right to privacy; right to dignity; right to file FIR; right to seek protection",
        "action_steps": (
            "1. Immediately report the incident to authorities 2. Preserve any "
            "available evidence 3. File FIR at nearest police station 4. Inform "
            "management (if location-based, like mall/hostel) 5. Seek support from "
            "trusted individuals"
        ),
        "timeline": "Immediate",
        "risks": "Misuse or circulation of content; emotional trauma; privacy breach",
        "edge_cases": "Recording in public vs private space; intentional vs accidental recording",
        "clarification_questions": "Was the recording done in a private area? Has the video been shared?",
        "source": "IPC Sec 354C; IT Act Sec 66E",
    },
    {
        "id": "SC-SH-16",
        "title": "Street Harassment (Catcalling)",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is facing verbal harassment such as catcalling, inappropriate comments, or gestures in a public place, making them feel unsafe.",
        "user_input_examples": [
            "People are passing comments on me on the street",
            "Someone is making inappropriate remarks in public",
            "I feel unsafe walking due to harassment",
        ],
        "applicable_laws": "IPC Section 509 (Word, gesture intended to insult modesty); IPC Section 294 (Obscene acts in public places)",
        "rights": "Right to safety in public spaces; right to file complaint against harassment; right to police protection",
        "action_steps": "1. Move to a safe and crowded area 2. Note details of the person (if safe) 3. Report incident to nearest police station 4. File a complaint if harassment continues",
        "timeline": "Immediate or as soon as possible",
        "risks": "Escalation into physical harassment; repeated targeting",
        "edge_cases": "Single incident vs repeated harassment; known vs unknown person",
        "clarification_questions": "Did the harassment happen repeatedly?",
        "source": "IPC Sec 509, 294",
    },
    {
        "id": "SC-SH-17",
        "title": "Online Stalking / Repeated Messaging",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is being repeatedly contacted or followed online despite lack of consent, causing distress.",
        "user_input_examples": [
            "Someone keeps messaging me repeatedly",
            "I blocked them but they keep contacting me",
            "I feel harassed online",
        ],
        "applicable_laws": "IPC Section 354D (Stalking); IT Act provisions",
        "rights": "Right to privacy; right to stop unwanted communication; right to file complaint",
        "action_steps": "1. Block the person 2. Save screenshots as evidence 3. Report on platform 4. File complaint if harassment continues",
        "timeline": "Immediate",
        "risks": "Escalation to threats; emotional distress",
        "edge_cases": "Known vs unknown person",
        "clarification_questions": "Is the person continuing after being blocked?",
        "source": "IPC Sec 354D",
    },
    {
        "id": "SC-SH-18",
        "title": "Threats After Breakup",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is receiving threats or harassment from a former partner, creating safety concerns.",
        "user_input_examples": [
            "My ex is threatening me",
            "I am getting threatening calls/messages",
            "They said they will harm me",
        ],
        "applicable_laws": "IPC Section 503 (Criminal intimidation); IPC Section 506 (Punishment for intimidation)",
        "rights": "Right to safety; right to file FIR; right to police protection",
        "action_steps": "1. Save messages/call records 2. Do not engage with the person 3. File police complaint 4. Inform trusted person",
        "timeline": "Immediate",
        "risks": "Escalation to physical harm; emotional stress",
        "edge_cases": "Online vs in-person threats",
        "clarification_questions": "Are the threats specific or general?",
        "source": "IPC Sec 503, 506",
    },
    {
        "id": "SC-SH-19",
        "title": "Harassment in PG/Hostel",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is facing harassment or unsafe conditions in shared accommodation like PG or hostel.",
        "user_input_examples": [
            "I feel unsafe in my PG",
            "Owner/roommate is harassing me",
            "Living environment is unsafe",
        ],
        "applicable_laws": "IPC provisions on harassment; local tenancy and safety regulations",
        "rights": "Right to safe accommodation; right to report harassment; right to leave unsafe environment",
        "action_steps": "1. Inform PG owner/authority 2. Document incidents 3. File complaint if needed 4. Seek alternative accommodation",
        "timeline": "As soon as possible",
        "risks": "Continued harassment; safety threats",
        "edge_cases": "Verbal vs physical harassment",
        "clarification_questions": "Is the harassment ongoing?",
        "source": "IPC General Provisions",
    },
    {
        "id": "SC-SH-20",
        "title": "Threatening Calls from Unknown Number",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is receiving threatening or abusive calls from unknown sources.",
        "user_input_examples": [
            "I am getting threatening calls",
            "Unknown number is scaring me",
            "Someone is calling and threatening",
        ],
        "applicable_laws": "IPC Section 507 (Criminal intimidation by anonymous communication)",
        "rights": "Right to safety; right to file FIR",
        "action_steps": "1. Do not engage 2. Save call records 3. Report to police 4. Block number",
        "timeline": "Immediate",
        "risks": "Continued harassment; escalation",
        "edge_cases": "Spam vs serious threat",
        "clarification_questions": "Are threats repeated?",
        "source": "IPC Sec 507",
    },
    {
        "id": "SC-SH-21",
        "title": "Cyberstalking / Repeated Online Monitoring",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is being repeatedly followed, monitored, or contacted online in a way that causes fear, discomfort, or invasion of privacy.",
        "user_input_examples": [
            "Someone keeps tracking my online activity",
            "They message me from multiple accounts",
            "I feel like I'm being watched online",
        ],
        "applicable_laws": "IPC Section 354D (Stalking); IT Act Section 66E (Violation of Privacy)",
        "rights": "Right to privacy; right to protection from harassment; right to file a complaint/FIR",
        "action_steps": (
            "1. Block all suspicious accounts 2. Take screenshots of messages and "
            "activity 3. Report accounts to the platform 4. File complaint with "
            "cybercrime portal or police 5. Inform trusted person for support"
        ),
        "timeline": "Immediate action recommended",
        "risks": "Escalation into offline stalking; emotional distress; identity misuse",
        "edge_cases": "Known person vs unknown; fake accounts vs real identity",
        "clarification_questions": "Is the same person contacting you repeatedly? Has any personal information been shared?",
        "source": "IPC Sec 354D; IT Act Sec 66E",
    },
    {
        "id": "SC-SH-22",
        "title": "Revenge Content / Threat to Share Private Media",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is being threatened with the release of private or sensitive content to harm their reputation or force compliance.",
        "user_input_examples": [
            "Someone is threatening to leak my private photos",
            "They are blackmailing me with personal content",
            "My ex is threatening me",
        ],
        "applicable_laws": "IT Act Section 67, 67A (Publishing or transmitting objectionable content); IPC Section 354C (Voyeurism); IPC Section 503 (Criminal intimidation)",
        "rights": "Right to privacy and dignity; right to protection from exploitation; right to file FIR",
        "action_steps": "1. Do not engage or comply with threats 2. Save all messages as evidence 3. Report content/accounts on platform 4. File FIR or cybercrime complaint 5. Seek immediate support",
        "timeline": "Immediate",
        "risks": "Content leakage; emotional trauma; social harm",
        "edge_cases": "Content already shared vs only threat; known vs unknown person",
        "clarification_questions": "Has any content already been shared? Do you know the person?",
        "source": "IT Act Sec 67, 67A; IPC Sec 354C, 503",
    },
    {
        "id": "SC-SH-23",
        "title": "Workplace Harassment (Non-Sexual)",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User is facing repeated hostile behavior, intimidation, or unfair treatment at the workplace affecting mental well-being.",
        "user_input_examples": [
            "My boss is mentally harassing me",
            "I'm being bullied at work",
            "I'm constantly targeted unfairly",
        ],
        "applicable_laws": "IPC Section 503 (Criminal intimidation); labour laws and workplace policies (company-level)",
        "rights": "Right to safe working environment; right to raise complaint internally; right to dignity",
        "action_steps": "1. Document incidents with proof 2. Report to HR or management 3. File written complaint 4. Escalate if no action taken",
        "timeline": "As soon as pattern of harassment is identified",
        "risks": "Career impact; stress and burnout; retaliation",
        "edge_cases": "Strict management vs harassment; peer vs senior",
        "clarification_questions": "Is the behavior repeated? Is there any written proof?",
        "source": "IPC Sec 503; Workplace Policies",
    },
    {
        "id": "SC-SH-24",
        "title": "Threats of Physical Harm",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User has received direct or indirect threats of physical harm, creating fear for personal safety.",
        "user_input_examples": [
            "Someone threatened to hurt me",
            "I received a threat message",
            "I'm scared for my safety",
        ],
        "applicable_laws": "IPC Section 503 (Criminal intimidation); IPC Section 506 (Punishment for intimidation)",
        "rights": "Right to personal safety; right to police protection; right to file FIR",
        "action_steps": "1. Preserve all evidence (messages, calls) 2. Avoid confrontation 3. Inform trusted person 4. File FIR at nearest police station 5. Seek police protection if needed",
        "timeline": "Immediate",
        "risks": "Escalation into actual violence; psychological stress",
        "edge_cases": "Verbal vs written threat; known vs unknown person",
        "clarification_questions": "Was the threat specific? Do you know the person?",
        "source": "IPC Sec 503, 506",
    },
    {
        "id": "SC-SH-25",
        "title": "Public Harassment / Eve-Teasing",
        "category": "Safety & Harassment",
        "jurisdiction": "India",
        "situation": "User experienced unwanted comments, gestures, or behavior in a public place causing discomfort or fear.",
        "user_input_examples": [
            "Someone passed inappropriate comments in public",
            "I was harassed on the street",
            "People were making me uncomfortable",
        ],
        "applicable_laws": "IPC Section 509 (Word, gesture or act intended to insult modesty); IPC Section 354A (Sexual harassment)",
        "rights": "Right to dignity; right to public safety; right to file complaint",
        "action_steps": "1. Move to a safe location 2. Seek help from nearby people 3. Note details of the person (if safe) 4. Report incident to police",
        "timeline": "Immediate or as soon as possible",
        "risks": "Repeat incidents; escalation",
        "edge_cases": "Verbal vs physical harassment; crowded vs isolated area",
        "clarification_questions": "Did the person follow or touch you?",
        "source": "IPC Sec 509, 354A",
    },
    {
        "id": "SC-01",
        "title": "Phone Theft in Public Place",
        "category": "Police/FIR",
        "jurisdiction": "India",
        "situation": "Your phone was stolen in a public place (e.g., metro, market).",
        "user_input_examples": [
            "My phone got stolen in the metro",
            "Someone pickpocketed my phone",
            "Lost my phone in market, what to do?",
        ],
        "applicable_laws": (
            "IPC Section 378 - Theft; IPC Section 379 - Punishment for theft; "
            "IMEI blocking via CEIR"
        ),
        "rights": (
            "You have the right to file an FIR under Code of Criminal Procedure for theft. "
            "Protection against theft under Indian Penal Code Section 378. Police must "
            "register it if it's a cognizable offence."
        ),
        "action_steps": (
            "Go to nearest police station -> Provide details (IMEI, location, time) "
            "-> Request FIR copy -> Block SIM and device"
        ),
        "timeline": "File FIR as soon as possible (preferably within 24-48 hours).",
        "risks": "Delay reduces recovery chances; missing IMEI makes tracking harder",
        "edge_cases": "Phone lost vs stolen; police refusing FIR",
        "clarification_questions": "Was the phone stolen or lost? Do you have the IMEI number?",
        "source": "CrPC Sec 154, IPC Sec 378, Constitution Art 14",
    },
    {
        "id": "SC-02",
        "title": "Police Refuse to File FIR",
        "category": "Police/FIR",
        "jurisdiction": "India",
        "situation": "Police refuse to register your complaint.",
        "user_input_examples": [
            "Police are not registering my complaint",
            "They refused to file FIR",
            "What to do if police deny FIR",
        ],
        "applicable_laws": "CrPC Sec 154; CrPC Sec 156(3); Constitution Art 32",
        "rights": (
            "Under Code of Criminal Procedure and right to legal remedy under "
            "Constitution of India, police must register FIR for cognizable offences"
        ),
        "action_steps": (
            "Request written refusal -> Escalate to SP/DCP -> File complaint online or via post"
        ),
        "timeline": "Act immediately after refusal",
        "risks": "Delay weakens case; evidence may be lost",
        "edge_cases": "Non-cognizable offence; lack of proof",
        "clarification_questions": "What type of complaint is it? Did police give a reason?",
        "source": "CrPC Sec 154, Constitution Art 32",
    },
    {
        "id": "SC-03",
        "title": "Online Scam / Fraud",
        "category": "Cyber / FIR",
        "jurisdiction": "India",
        "situation": "You were scammed via UPI, website, or social media.",
        "user_input_examples": [
            "Money got deducted in scam",
            "I was cheated online",
            "UPI fraud happened",
        ],
        "applicable_laws": "IPC Sec 420; IT Act Sec 66D",
        "rights": (
            "Fraud is punishable under Indian Penal Code. Right to property protection "
            "under Constitution of India."
        ),
        "action_steps": (
            "Call cybercrime helpline (1930) -> File complaint on cybercrime portal -> Register FIR"
        ),
        "timeline": "Report within hours for best chance of recovery.",
        "risks": "Funds unrecoverable if delayed; fake recovery agents",
        "edge_cases": "Small amount vs large fraud; known scammer",
        "clarification_questions": "When did the transaction happen? Which platform was used?",
        "source": "IPC Sec 420, IT Act 2000, Constitution Art 300A",
    },
    {
        "id": "SC-04",
        "title": "Physical Assault (Minor Injury)",
        "category": "Police/FIR",
        "jurisdiction": "India",
        "situation": "You were physically assaulted (minor injuries).",
        "user_input_examples": [
            "Someone hit me",
            "I was physically attacked",
            "Minor injuries after fight",
        ],
        "applicable_laws": "IPC Sec 351; IPC Sec 352; IPC Sec 323",
        "rights": (
            "You can file FIR under assault provisions of Indian Penal Code. Right to "
            "life and personal liberty under Constitution of India"
        ),
        "action_steps": (
            "1. Seek medical help 2. Take photos of injuries "
            "3. File FIR 4. Collect witness details"
        ),
        "timeline": "Immediately or within 24 hours.",
        "risks": "No medical record weakens case",
        "edge_cases": "Self-defense situation; no witnesses",
        "clarification_questions": "Were there injuries? Any witnesses present?",
        "source": "IPC Sec 351-352, Constitution Art 21",
    },
    {
        "id": "SC-05",
        "title": "Harassment / Threats (Offline)",
        "category": "Safety / FIR",
        "jurisdiction": "India",
        "situation": "Someone is threatening or harassing you.",
        "user_input_examples": [
            "Someone is threatening me",
            "I feel unsafe",
            "I am being harassed",
        ],
        "applicable_laws": "IPC Sec 503; IPC Sec 506",
        "rights": (
            "Criminal intimidation is punishable under Indian Penal Code. Right to "
            "safety under Constitution of India."
        ),
        "action_steps": "Record evidence -> File FIR -> Inform trusted person",
        "timeline": "Immediate reporting recommended.",
        "risks": "Escalation if ignored",
        "edge_cases": "Known person; repeated threats",
        "clarification_questions": "Was there a direct threat?",
        "source": "IPC Sec 506, Constitution Art 21",
    },
    {
        "id": "SC-06",
        "title": "Cyberbullying / Online Harassment",
        "category": "Cyber",
        "jurisdiction": "India",
        "situation": "You're being harassed online (DMs, posts).",
        "user_input_examples": [
            "I am being bullied online",
            "Someone is posting about me",
            "I am getting hate messages",
        ],
        "applicable_laws": "IT Act Sec 66E; IPC Sec 509",
        "rights": (
            "You can report under IT laws & Indian Penal Code provisions. Right to "
            "dignity under Constitution of India."
        ),
        "action_steps": "1. Take screenshots 2. Report on platform 3. File complaint",
        "timeline": "As soon as harassment starts. Immediate.",
        "risks": "Evidence deletion",
        "edge_cases": "Anonymous account",
        "clarification_questions": "Is it public or private harassment?",
        "source": "IT Act 2000, IPC, Constitution Art 21",
    },
    {
        "id": "SC-07",
        "title": "Lost Wallet",
        "category": "Police / NCR",
        "jurisdiction": "India",
        "situation": "You lost your wallet containing ID and cash.",
        "user_input_examples": [
            "I lost my wallet",
            "My ID and money are missing",
        ],
        "applicable_laws": (
            "NCR (Non-Cognizable Report) concept; no specific IPC unless theft suspected"
        ),
        "rights": (
            "You can file a 'lost report' (non-cognizable entry). Protection from "
            "misuse under Constitution of India."
        ),
        "action_steps": "Visit police station -> File lost report -> Block cards immediately",
        "timeline": "Same day if possible.",
        "risks": "Identity misuse; financial fraud",
        "edge_cases": "Theft suspicion",
        "clarification_questions": "Was it lost or stolen?",
        "source": "Police procedures, Constitution Art 21",
    },
    {
        "id": "SC-08",
        "title": "False Complaint Against You",
        "category": "Legal Defense",
        "jurisdiction": "India",
        "situation": "Someone filed a false complaint naming you.",
        "user_input_examples": [
            "Someone filed false case on me",
            "I got legal notice wrongly",
        ],
        "applicable_laws": "IPC Section 182 - False information; IPC Section 211 - False charge",
        "rights": (
            "You have the right to defend and seek legal counsel under Indian Penal "
            "Code protections. Right to fair trial under Constitution of India"
        ),
        "action_steps": "Do not panic -> Consult lawyer -> Cooperate with investigation",
        "timeline": "Act immediately upon notice.",
        "risks": "Ignoring summons worsens situation",
        "edge_cases": "Civil vs criminal case",
        "clarification_questions": "What type of case is filed?",
        "source": "IPC Sec 211, Constitution Art 21",
    },
    {
        "id": "SC-09",
        "title": "Public Harassment (Eve-Teasing)",
        "category": "Safety",
        "jurisdiction": "India",
        "situation": "You faced harassment in a public place.",
        "user_input_examples": [
            "Someone harassed me in public",
            "I faced eve teasing",
        ],
        "applicable_laws": (
            "IPC Section 354 - Assault on woman; IPC Section 354A - Sexual "
            "harassment; IPC Section 509 - Insulting modesty"
        ),
        "rights": (
            "Protected under provisions of Indian Penal Code Section 354. Right to "
            "dignity under Constitution of India"
        ),
        "action_steps": "Seek help immediately -> File FIR -> Use women helpline (1091)",
        "timeline": "Immediate reporting preferred.",
        "risks": "Perpetrator may escape",
        "edge_cases": "Crowded area",
        "clarification_questions": "Can you identify the person?",
        "source": "IPC Sec 354, Constitution Art 21",
    },
    {
        "id": "SC-10",
        "title": "Illegal Police Detention",
        "category": "Legal Rights",
        "jurisdiction": "India",
        "situation": "Police detain you without telling why.",
        "user_input_examples": [
            "Police detained me without reason",
            "I was held without explanation",
        ],
        "applicable_laws": (
            "CrPC Section 50 - Right to know grounds; CrPC Section 57 - Cannot "
            "detain more than 24 hours without magistrate"
        ),
        "rights": (
            "You have the right to know grounds of arrest under Code of Criminal "
            "Procedure. Right to personal liberty under Constitution of India."
        ),
        "action_steps": (
            "Ask reason for detention -> Inform family/lawyer -> Do not resist physically"
        ),
        "timeline": "Immediate action required.",
        "risks": "Misunderstanding rights; escalation",
        "edge_cases": "Preventive detention",
        "clarification_questions": "Were you formally arrested?",
        "source": "CrPC Sec 50, Constitution Art 21",
    },
    {
        "id": "SC-11",
        "title": "Lost Mobile Phone (Not Stolen)",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "The user has lost their phone without clear evidence of theft.",
        "user_input_examples": [
            "I lost my phone",
            "Phone missing",
            "I can't find my mobile",
        ],
        "applicable_laws": "Non-Cognizable Report (NCR) procedure",
        "rights": "Right to file lost property report; right to receive acknowledgment",
        "action_steps": "1. Visit nearest police station 2. File lost report (NCR) 3. Block SIM and IMEI 4. Inform service provider",
        "timeline": "Same day",
        "risks": "Data misuse; fraud",
        "edge_cases": "Lost vs stolen",
        "clarification_questions": "Do you suspect theft?",
        "source": "Police NCR Procedure",
    },
    {
        "id": "SC-12",
        "title": "Theft of Wallet",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "User's wallet has been stolen, possibly containing cash and important documents.",
        "user_input_examples": [
            "My wallet got stolen",
            "Lost wallet with money",
        ],
        "applicable_laws": "IPC Section 379 (Theft)",
        "rights": "Right to file FIR; police must register FIR",
        "action_steps": "1. File FIR 2. Block cards 3. Inform bank",
        "timeline": "Immediate",
        "risks": "Financial fraud",
        "edge_cases": "Lost vs stolen",
        "clarification_questions": "Any suspicious activity?",
        "source": "IPC Sec 379",
    },
    {
        "id": "SC-13",
        "title": "Minor Road Accident",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "A minor accident has occurred with property damage but no major injuries.",
        "user_input_examples": [
            "I got into a small accident",
            "Minor car damage happened",
            "No injuries but damage occurred",
        ],
        "applicable_laws": "Motor Vehicles Act",
        "rights": "Right to report incident; right to claim insurance",
        "action_steps": "1. Exchange details with other party 2. Take photos of damage 3. Inform insurance company 4. Report to police if dispute arises",
        "timeline": "Same day",
        "risks": "Insurance claim issues; disputes",
        "edge_cases": "Disagreement on fault",
        "clarification_questions": "Was anyone injured?",
        "source": "Motor Vehicles Act",
    },
    {
        "id": "SC-14",
        "title": "Hit and Run Case",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "The user's vehicle/person was hit and the offender fled the scene.",
        "user_input_examples": [
            "Someone hit my vehicle and ran away",
            "I couldn't identify the driver",
        ],
        "applicable_laws": "IPC provisions; Motor Vehicles Act",
        "rights": "Right to file FIR; right to compensation",
        "action_steps": "1. Note vehicle details if possible 2. File FIR immediately 3. Inform insurance 4. Seek medical help if needed",
        "timeline": "Immediate",
        "risks": "Difficulty identifying accused",
        "edge_cases": "No witnesses",
        "clarification_questions": "Do you have vehicle number?",
        "source": "Motor Vehicles Act",
    },
    {
        "id": "SC-15",
        "title": "Identity Theft / Online Fraud",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "User's personal information has been misused for fraudulent activities.",
        "user_input_examples": [
            "Someone used my identity online",
            "Fraud happened using my details",
        ],
        "applicable_laws": "IT Act Section 66C; IPC Section 420",
        "rights": "Right to file FIR; right to protection against fraud",
        "action_steps": "1. Report to cybercrime portal 2. Inform bank 3. File FIR 4. Freeze transactions",
        "timeline": "Immediate",
        "risks": "Financial loss; identity misuse",
        "edge_cases": "Known vs unknown fraudster",
        "clarification_questions": "Was money lost?",
        "source": "IT Act Sec 66C; IPC Sec 420",
    },
    {
        "id": "SC-16",
        "title": "Lost Mobile Phone (Uncertain Theft)",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "The user has misplaced their phone but is unsure whether it was stolen or lost.",
        "user_input_examples": [
            "I lost my phone somewhere",
            "My phone is missing",
            "I can't find my phone",
        ],
        "applicable_laws": "General Diary Entry (Lost Report); CrPC Section 154 (if theft suspected later)",
        "rights": "Right to file a lost report; right to file FIR if theft is confirmed",
        "action_steps": (
            "1. Try locating via tracking apps 2. Block SIM and device 3. Visit police "
            "station and file report 4. Keep report copy 5. Convert to FIR if theft is suspected"
        ),
        "timeline": "Within 24 hours",
        "risks": "Data misuse; difficulty in recovery",
        "edge_cases": "Lost vs stolen confusion",
        "clarification_questions": "Do you suspect theft? Do you have IMEI?",
        "source": "CrPC Sec 154",
    },
    {
        "id": "SC-17",
        "title": "Police Refusal to Register FIR",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "The police have refused to register an FIR for a cognizable offence.",
        "user_input_examples": [
            "Police refused to file FIR",
            "They are not taking my complaint",
            "What should I do?",
        ],
        "applicable_laws": "CrPC Section 154; Lalita Kumari vs Govt. of UP (Supreme Court Judgment)",
        "rights": "Right to mandatory FIR; right to escalate complaint",
        "action_steps": "1. Ask for written refusal 2. Approach senior officer 3. Send written complaint 4. Approach Magistrate",
        "timeline": "Immediate",
        "risks": "Delay in justice; evidence loss",
        "edge_cases": "Cognizable vs non-cognizable",
        "clarification_questions": "What offence did you report?",
        "source": "CrPC Sec 154; Lalita Kumari Case",
    },
    {
        "id": "SC-18",
        "title": "Online Payment Fraud (Bank Account)",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "User lost money due to an online fraud or scam.",
        "user_input_examples": [
            "I got scammed online",
            "Money deducted from account",
            "Fraud through UPI",
        ],
        "applicable_laws": "IPC Section 420; IT Act Section 66C, 66D",
        "rights": "Right to file FIR; right to report cybercrime",
        "action_steps": "1. Inform bank immediately 2. Call cyber helpline (1930) 3. File complaint online 4. File FIR 5. Save proof",
        "timeline": "Within hours",
        "risks": "Financial loss; identity misuse",
        "edge_cases": "OTP sharing",
        "clarification_questions": "How did fraud happen?",
        "source": "IPC Sec 420; IT Act Sec 66C, 66D",
    },
    {
        "id": "SC-19",
        "title": "Physical Assault (General)",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "User was physically attacked or harmed.",
        "user_input_examples": [
            "Someone hit me",
            "I got injured in fight",
            "I was assaulted",
        ],
        "applicable_laws": "IPC Section 323; IPC Section 351",
        "rights": "Right to file FIR; right to medical care",
        "action_steps": "1. Seek medical help 2. Collect report 3. File FIR 4. Provide evidence",
        "timeline": "Immediate",
        "risks": "Injury escalation",
        "edge_cases": "Self-defense",
        "clarification_questions": "Was injury serious?",
        "source": "IPC Sec 323, 351",
    },
    {
        "id": "SC-20",
        "title": "Missing Person Complaint",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "A person cannot be located and is missing.",
        "user_input_examples": [
            "Someone is missing",
            "Not reachable",
            "Didn't return home",
        ],
        "applicable_laws": "Police Guidelines; FIR if foul play suspected",
        "rights": "Right to file report immediately",
        "action_steps": "1. File complaint 2. Provide details 3. Share last location 4. Follow up",
        "timeline": "Immediate",
        "risks": "Delay reduces recovery",
        "edge_cases": "Minor vs adult",
        "clarification_questions": "When last seen?",
        "source": "Police Guidelines",
    },
    {
        "id": "SC-21",
        "title": "Threatening Messages (General)",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "User is receiving threatening communication.",
        "user_input_examples": [
            "I received threats",
            "Someone is threatening me",
            "Abusive messages",
        ],
        "applicable_laws": "IPC Section 503; IPC Section 506",
        "rights": "Right to safety; right to file FIR",
        "action_steps": "1. Save evidence 2. Avoid replying 3. File FIR",
        "timeline": "Immediate",
        "risks": "Escalation",
        "edge_cases": "Unknown sender",
        "clarification_questions": "Was threat serious?",
        "source": "IPC Sec 503, 506",
    },
    {
        "id": "SC-22",
        "title": "Wallet Theft (Documents & Cards)",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "User lost or had their wallet stolen.",
        "user_input_examples": [
            "Wallet stolen",
            "Lost documents",
            "Missing cards",
        ],
        "applicable_laws": "IPC Section 379",
        "rights": "Right to file FIR",
        "action_steps": "1. File report 2. Block cards 3. Reissue documents",
        "timeline": "Immediate",
        "risks": "Identity misuse",
        "edge_cases": "Lost vs stolen",
        "clarification_questions": "What was inside wallet?",
        "source": "IPC Sec 379",
    },
    {
        "id": "SC-23",
        "title": "Property Damage",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "User's property is intentionally damaged.",
        "user_input_examples": [
            "Property damaged",
            "Vehicle vandalized",
        ],
        "applicable_laws": "IPC Section 427",
        "rights": "Right to file FIR",
        "action_steps": "1. Take evidence 2. File FIR",
        "timeline": "Immediate",
        "risks": "Financial loss",
        "edge_cases": "Intent unclear",
        "clarification_questions": "Who caused damage?",
        "source": "IPC Sec 427",
    },
    {
        "id": "SC-24",
        "title": "Fake Social Media Profile (Identity Misuse)",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "User's identity is being misused online.",
        "user_input_examples": [
            "Fake account in my name",
            "Identity misuse",
        ],
        "applicable_laws": "IT Act Section 66C; IT Act Section 66D",
        "rights": "Right to privacy; right to file complaint",
        "action_steps": "1. Report account 2. Take screenshots 3. File cyber complaint",
        "timeline": "Immediate",
        "risks": "Reputation damage",
        "edge_cases": "Parody vs fraud",
        "clarification_questions": "Has harm occurred?",
        "source": "IT Act Sec 66C, 66D",
    },
    {
        "id": "SC-25",
        "title": "Minor Road Accident (Collision)",
        "category": "Police / FIR",
        "jurisdiction": "India",
        "situation": "User was involved in a minor vehicle accident.",
        "user_input_examples": [
            "Small accident",
            "Minor collision",
        ],
        "applicable_laws": "Motor Vehicles Act; IPC Section 279",
        "rights": "Right to report; right to claim insurance",
        "action_steps": "1. Ensure safety 2. Exchange details 3. Take photos 4. Inform police if needed",
        "timeline": "Immediate",
        "risks": "Future disputes",
        "edge_cases": "Injury vs no injury",
        "clarification_questions": "Any injuries?",
        "source": "Motor Vehicles Act; IPC Sec 279",
    }, # CRLF (\r\n)
] # CRLF (\r\n)
#End-of-file (EOF)